## Importar les Dades

Sources

1. [Registre central de població del CatSalut](https://catsalut.gencat.cat/ca/proveidors-professionals/registres-catalegs/registres/central-poblacio/) posa a disposició les dades al portal [Dades Obertes.](https://analisi.transparenciacatalunya.cat/Salut/Registre-central-de-poblaci-del-CatSalut-poblaci-p/ftq4-h9vk)
Així com també un [informe](https://catsalut.gencat.cat/web/.content/minisite/catsalut/proveidors_professionals/registres_catalegs/documents/informe-poblacio-referencia-2021.pdf) en format pdf. 

2. [Catàleg ABS](https://catsalut.gencat.cat/ca/proveidors-professionals/registres-catalegs/catalegs/territorials-unitats-proveidores/)

Nota: Malgrat que no s'ha calculat la població a nivell d'AGA això també seria possible seguint el mateix procediment amb aquestes [dades](https://catsalut.gencat.cat/ca/proveidors-professionals/registres-catalegs/catalegs/territorials-unitats-proveidores/).

In [8]:
import pandas as pd
abs = pd.read_csv("/content/2021_registre_central_poblacio_per_abs_catsalut.csv")
f = {'codi Àrea Bàsica de Saut': 'first', 'Àrea Bàsica de Salut': 'first', 'població oficial': 'sum'}
abs = abs.groupby(['Àrea Bàsica de Salut'], as_index=False).agg(f)
abs.head(3)

   codi Àrea Bàsica de Saut Àrea Bàsica de Salut  població oficial
0                       370               ABRERA             12388
1                         1             AGRAMUNT              6486
2                         2             ALCARRÀS             14018

In [9]:
ss = pd.read_csv('/content/06-Cataleg ABS.csv')
ss.head(3)

   codi municipi descripcio municipi  ...  codi localitat descripcio localitat
0           8001              Abrera  ...          800100               ABRERA
1           8001              Abrera  ...          800101               ABRERA
2           8001              Abrera  ...          800102            CA N'AMAT

[3 rows x 10 columns]

In [10]:
ss = ss.merge(abs, how='left', right_on='codi Àrea Bàsica de Saut', left_on='codi ABS')
ss.drop(labels=['codi Àrea Bàsica de Saut', 'Àrea Bàsica de Salut'], axis=1, inplace=True)
ss.head(3)

   codi municipi descripcio municipi  ...  descripcio localitat població oficial
0           8001              Abrera  ...                ABRERA          12388.0
1           8001              Abrera  ...                ABRERA          12388.0
2           8001              Abrera  ...             CA N'AMAT          12388.0

[3 rows x 11 columns]

## Població per Àrea Bàsica de Salut (ABS)

In [11]:
f = {'codi ABS': 'first', 'descripcio ABS': 'first', 'codi SS': 'first', 'descripcio SS': 'first', 'codi RS': 'first', 'descripcio RS': 'first', 'població oficial': 'mean'}
absp = ss.groupby(['codi ABS'], as_index=False).agg(f)
absp.to_csv('/content/abs_poblacio.csv', index=False)
absp.head(3)

   codi ABS     descripcio ABS  ...  descripcio RS població oficial
0         1           Agramunt  ...         Lleida           6486.0
1         2           Alcarràs  ...         Lleida          14018.0
2         3  Alfarràs/ Almenar  ...         Lleida           9715.0

[3 rows x 7 columns]

## Població per Sector Sanitari (SS)

In [12]:
f = {'codi SS': 'first', 'descripcio SS': 'first', 'descripcio SS': 'first', 'codi RS': 'first', 'descripcio RS': 'first', 'població oficial': 'sum'}
ssp = absp.groupby(['codi SS'], as_index=False).agg(f)
ssp.to_csv('/content/ss_poblacio.csv', index=False)
ssp.head(3)

   codi SS              descripcio SS  ...      descripcio RS població oficial
0     6156                     Lleida  ...             Lleida         365322.0
1     6257  Alt Camp-Conca de Barberà  ...  Camp de Tarragona          61667.0
2     6258    Tarragonès-Baix Penedès  ...  Camp de Tarragona         350371.0

[3 rows x 5 columns]

## Població per Regió Sanitària (RS)

In [13]:
# poblacio per regio sanitaria
f = {'codi RS': 'first', 'descripcio RS': 'first', 'població oficial': 'sum'}
rsp = ssp.groupby(['codi RS'], as_index=False).agg(f)
rsp.to_csv('/content/rs_poblacio.csv', index=False)
rsp.head(3)

   codi RS      descripcio RS  població oficial
0       61             Lleida          365322.0
1       62  Camp de Tarragona          614830.0
2       63   Terres de l'Ebre          178112.0

## Població Total Catalunya (2021) en millions d'habitans

In [15]:
rsp['població oficial'].sum() / 10**6

7.697069